# Beginner Level (1-40)

## 1. Create an Array of Zeros
📝 Task: Write a function that creates a 2D array filled with zeros, given the array's shape.
### Answer:
```python
# Function to implement
def create_zeros_array(rows: int, cols: int) -> np.ndarray:
    """
    Returns a 2D array filled with zeros of shape (rows, cols).
    """
    pass

# Example:
# Input: rows = 3, cols = 4
# Output:
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]
```

In [2]:
import numpy as np

def create_zeros_array(rows: int, cols: int):
    return np.zeros((rows, cols))

print(create_zeros_array(3, 4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 2. Generate a Sequence of Numbers
📝 Task: Implement a function that returns an array of integers from start to end (exclusive) with a given step size.
### Answer:
```python
# Function to implement
def generate_sequence(start: int, end: int, step: int) -> np.ndarray:
    """
    Returns an array with a sequence of numbers from start to end with a specified step.
    """
    pass

# Example:
# Input: start = 0, end = 10, step = 2
# Output: [0 2 4 6 8]

```

In [3]:
def generate_sequence(start: int, end: int, step: int):
    return np.arange(start, end, step)

print(generate_sequence(0, 10, 2))

[0 2 4 6 8]


## 3. Find Even Numbers in an Array
📝 Task: Given an array of integers, return a new array containing only even numbers.
```python
def filter_even_numbers(arr: np.ndarray) -> np.ndarray:
    """
    Returns an array containing only even numbers from the input array.
    """
    pass

# Example:
# Input: arr = np.array([1, 2, 3, 4, 5, 6])
# Output: [2 4 6]
```

In [4]:
def filter_even_numbers(arr:np.ndarray) -> np.ndarray:
    return arr[arr % 2 == 0]

print(filter_even_numbers(np.array([1, 2, 3, 4, 5, 6])))

[2 4 6]


---
### 4. Matrix Multiplication
📝 Task: Implement a function that multiplies two 2D matrices using NumPy.
```python
def multiply_matrices(mat1: np.ndarray, mat2: np.ndarray) -> np.ndarray:
    """
    Returns the product of two matrices mat1 and mat2.
    """
    pass

# Example:
# Input: 
# mat1 = np.array([[1, 2], [3, 4]])
# mat2 = np.array([[2, 0], [1, 2]])
# Output:
# [[4 4]
#  [10 8]]
```

In [1]:
def multiply_matrices(mat1, mat2):
    return np.dot(mat1, mat2)

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[2, 0], [1, 2]])
print(multiply_matrices(mat1, mat2))

NameError: name 'np' is not defined