# 101 NumPy exercises
## In this notebook I'm going to solve 101 NumPy exercises from [Machine Learning Plus](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

### Q. Import numpy as np and print the version number.

In [2]:
import numpy as np
print(np.__version__)

2.2.3


---
### Q. Create a 1D array of numbers from 0 to 9

In [2]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


---
### Create a 3×3 numpy array of all True’s

In [3]:
array = np.full((3, 3), True, dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


---
### Q. Extract all odd numbers from arr
#### Input:
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
#### Output:
```python
#> array([1, 3, 5, 7, 9])
```

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = arr % 2 != 0

odd_numbers = arr[mask]
print(odd_numbers)

[1 3 5 7 9]


---
### Q. Replace all odd numbers in arr with -1

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


---
### Q. Replace all odd numbers in arr with -1 without changing arr

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 != 0, -1, arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


---
### Q. Convert a 1D array to a 2D array with 2 rows

In [20]:
arr = np.arange(10)
reshaped_arr = arr.reshape(2, -1)
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


---
### Q. Stack arrays a and b vertically

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

r = np.vstack([a, b])
print(r)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


---
### Q. Stack the arrays a and b horizontally.

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

r = np.hstack([a, b])
print(r)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


---
### Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [25]:
a = np.array([1,2,3])
# #> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

r = np.hstack([np.repeat(a, 3), np.tile(a, 3)])
print(r)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


---
### Q. Get the common items between a and b

In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# >> OUTPUT : array([2, 4])

r = np.intersect1d(a, b)
print(r)

[2 4]


---
### Q. From array a remove all items present in array b



In [4]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

r = np.setdiff1d(a, b)
print(r)

[1 2 3 4]


---
### Q. Get the positions where elements of a and b match

In [5]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

r = np.where(a == b)
print(r)

(array([1, 3, 5, 7]),)


---
### Q. Get all items between 5 and 10 from a.

In [7]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
r = a [np.where((a >= 5) & (a <= 10))]
print(r)

[ 6  9 10]


---
### Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [9]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


---
### Q. Swap columns 1 and 2 in the array arr.

In [11]:
arr = np.arange(9).reshape(3,3)
print(arr) # before

arr = arr[:, [1,0,2]]
print(arr) # after

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


---
### Q. Swap rows 1 and 2 in the array arr:

In [13]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr = arr[[1,0,2], :] # swap rows
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


---
### Q. Reverse the rows of a 2D array arr.

In [17]:
# Input
arr = np.arange(9).reshape(3,3)
print(arr)
arr = arr[::-1]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


---
### Q. Reverse the columns of a 2D array arr.

In [18]:
# Input
arr = np.arange(9).reshape(3,3)
print(arr)

arr = arr[:, ::-1]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


---
### Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [19]:
arr = np.random.uniform(5,10, size=(5,3))
print(arr)

[[6.37652682 9.18114815 9.66883926]
 [8.64075078 6.93851586 5.86377778]
 [9.53587895 9.54113521 6.68043356]
 [5.12854711 7.11842756 5.44139844]
 [6.12565736 6.15955936 9.71859621]]
