# 101 NumPy exercises
## In this notebook I'm going to solve 101 NumPy exercises from [Machine Learning Plus](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

### Q. Import numpy as np and print the version number.

In [1]:
import numpy as np
print(np.__version__)

2.2.3


---
### Q. Create a 1D array of numbers from 0 to 9

In [2]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


---
### Create a 3×3 numpy array of all True’s

In [3]:
array = np.full((3, 3), True, dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


---
### Q. Extract all odd numbers from arr
#### Input:
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
#### Output:
```python
#> array([1, 3, 5, 7, 9])
```

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = arr % 2 != 0

odd_numbers = arr[mask]
print(odd_numbers)

[1 3 5 7 9]


---
### Q. Replace all odd numbers in arr with -1

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


---
### Q. Replace all odd numbers in arr with -1 without changing arr

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 != 0, -1, arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


---
### Q. Convert a 1D array to a 2D array with 2 rows

In [20]:
arr = np.arange(10)
reshaped_arr = arr.reshape(2, -1)
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


---
### Q. Stack arrays a and b vertically

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

r = np.vstack([a, b])
print(r)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


---
### Q. Stack the arrays a and b horizontally.

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

r = np.hstack([a, b])
print(r)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


---
### Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [25]:
a = np.array([1,2,3])
# #> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

r = np.hstack([np.repeat(a, 3), np.tile(a, 3)])
print(r)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
